template: recipe
directory: recipe
title: Apple Crumble Tart
card_photo: /recipes/apple_crumble_tart/Apple_Tart_Square.jpg
featured: false
instagram: https://www.instagram.com/p/Brk2WcXhZ3L/?utm_source=ig_web_copy_link
print: /recipes/apple_crumble_tart/Apple_Crumble_Tart.pdf
date: 25/06/2020
description: |
  Maybe not quite your Grandma’s apple crumble, but this is a really tasty alternative. A sweet pastry base, cinnamon apple layer, creme patisserie for the custard and a healthy layer of nutty crumble on top. Yum.
tags:
  - tart
  - apple
images:
  - /recipes/apple_crumble_tart/Apple_Tart_Square.jpg
ingredients:
  - 1x quantity of sweet pastry
  - 0.5x quantity of creme patisserie
  - 4 large eating apples
  - 1tsp cinnamon
  - 1tsp mixed spice
  - 150g plain flour
  - 60g caster sugar
  - 100g unsalted butter
method:
  - Make the pastry and blind bake as in separate recipe, making sure the case is dry on the bottom and golden. Cool completely.
  - Whilst the pastry is cooking, make the crumble. Place all the ingredients in a bowl and rub them together to create breadcrumbs. Place the mix on a baking tray and cook for about 10 minutes, or until golden brown. Leave to cool completely.
  - Make the creme patisserie, as in separate recipe and cool completely. Make sure, if you are leaving it for a long time, to cover it completely with clingfilm so that a skin does not form.
  - Prepare the apples. Core and thinly slice the apples, trying to be quick so that they do not brown. Place in a large saucepan with the spices and mix over a medium heat for 1-2 minutes. They should have just lost their rawness but keep some crunch.
  - Assemble. Fill the bottom half of the tart case with the pastry cream, smoothing it down to create a flat surface. On top, place the apples in an even layer and completely cover the apples. Serve chilled with a sprinkle of icing sugar.
