template: recipe
directory: recipe
title: Addictive Chocolate Biscuits
card_photo: /recipes/chocolate_biscuits/Moreish_Chocolate_Biscuits.jpg
instagram: https://www.instagram.com/p/Bowkm0TluPF/?utm_source=ig_web_copy_link
featured: false
description: |
  I think it’s only right to attach a warning to these biscuits, you will not stop eating them. They are also really simple to make and will definitely impress.
tags:
  - chocolate
  - biscuits
images:
  - /recipes/chocolate_biscuits/Moreish_Chocolate_Biscuits.jpg
ingredients:
  - 200g plain flour
  - 25g cocoa powder
  - 80g soft brown sugar
  - 200g chilled butter
  - 50g dark chocolate
  - 1 tbsp condensed milk
method:
  - Place the flour, cocoa powder and brown sugar in a bowl and mix together. Cut the butter into small pieces and rub into the dry ingredients with your finger tips. This will turn into a soft dough, but try to remove the large pieces of butter.
  - Finely chop the chocolate and mix into the dough with the condensed milk. Once combined, roll the dough into two logs and place in the fridge to chill for 30 minutes. Preheat the oven to 180ºC.
  - When the logs are chilled, cut them into 1cm rounds and place on baking trays, with eat least 1cm surrounding them. Bake for 12-15 minutes. Once cooked leave until solid and then cool completely on a cooling rack.
