template: recipe
directory: recipe
title: Chocolate Celebration Cake
card_photo: /recipes/chocolate_celebration_cake/cake_square.jpg
featured: true
description: |
  A really yummy chocolate cake.
  With Cointreau truffles.
  Some extra words to pad out the box.
  Magical unicorns fly gracefully over the rainbow.
tags:
  - Cake
  - Chocolate
  - Yummy
images:
  - /recipes/chocolate_celebration_cake/cake_square.jpg
ingredients:
  - 150g dark chocolate
  - Butter for greasing
  - Dry Ingredients:
    - 280g flour
    - 70g cocoa powser
    - 1.5 tsp baking powder
    - pinch of salt
    - 300g caster sugar
  - Wet Ingredients:
    - 360ml of water
    - 112g oil (vegetable or sunflower)
    - 1.5 tbsp apple cider or white wine vinegar
    - 1tsp vanilla essence
  - Chocolate ganache:
    - 150g dark chocolate
    - 120g double cream
    - 30g liquid glucose
method:
  - Preheat the oven to 170ºC/160ºC fan. Prepare the cake tins. Grease around the sides and bottom of the tins, add a circle of greaseproof to the bottom of the tins.
  - Finely chop the dark chocolate. Sieve all dry ingredients into a bowl, whisking together to make sure that they are thoroughly combined. In another bowl mix together the wet ingredients. When ready gently mix the wet ingredients into the dry, adding the chocolate pieces half way through. Do not over mix. Immediately pour into the cake tins, evenly.
  - Cook for 30 mins. Test the cakes, if not cooked keep cooking for 5 minutes at a time until a cake tester comes out clean. Cool on a wire rack until room temperature.
  - Whilst the cakes are cooling make the ganache. Finely chop the chocolate and place in a bowl. Add the cream and liquid glucose to a shallow pan and heat until just before boiling. Add the cream to the chocolate in 3 parts, gently stirring after each addition to slowly melt the chocolate. Cool in the fridge for approximately 25 minutes, or until thickened but with a spreadable consistency.
  - Assemble the cake. Trim the cakes so that they are almost flat, then place the first layer on a plate or cake board. Add a thick layer of ganache, and then repeat. Crumb coat the sides of the cake and fill in any gaps around the sides. Then add the last of the ganache to the sides and top of the cake. Using a scraper or clean ruler, slowly scrape the sides of the cake until the ganache is smooth, using the plate to spin the cake for you. Use the same scraper to flatten the top. Cool in the fridge until ready to eat.
  - This cake is best served the next day, when the ganache has started to seep into the layers.
  - <h3><b>Alterations</b></h3>
  - This cake was made as a chocolate orange cake, with a layer of eggless orange curd. I then decorated it with Cointreau truffles and white chocolate shards coloured orange. I think that the dark chocolate gives the cake an amazing richness, but feel free to use milk chocolate and any other flavoured fillings. Caramelised almonds would work perfectly on top.
