template: recipe
directory: recipe
title: Basic Sweet Pastry
card_photo: /recipes/sweet_pastry/basic_sweet_pastry.jpg
featured: false
description: |
  I have been using this recipe for sweet pastry since I started making eggless recipe and it hasn’t failed me yet!
  Once you crack the pastry shell it opens up a world of possibilities, holding any sort of fruity, custardy, chocolatey mess you can think of - trust me they’re very forgiving. Here I just give a guide to making the pastry dough, see my other recipe for blind baking.
tags:
  - pastry
images:
  - /recipes/sweet_pastry/basic_sweet_pastry.jpg
ingredients:
  - 200g plain flour (all-purpose)
  - 70g sugar
  - 130g butter, chilled and cut into small cubes
  - About 25ml of milk
method:
  - Add the flour, sugar and butter to a large mixing bowl. With your thumb and fingertips, rub the butter into the flour until it resembles breadcrumbs.
  - It is important here to only use the tips of your fingers and not the palms of your hands, the heat will melt the butter and the cooler the butter the shorter the pastry. Similarly, try not to overwork it, if it seems to be on the point of breadcrumbs, leave it. Small lumps of butter never hurt anyone.
  - Add a tbsp of milk to the breadcrumbs and stir with a knife to bring them together. Gradually add 1tsp at a time until it resembles a soft, but not sticky, dough. Wrap in clingfilm and rest in the fridge for 20 minutes (or as specified in the recipe). 
