template: recipe
directory: recipe
title: Blind Baking
card_photo: /recipes/blind_baking/Blind_Baking.jpg
featured: false
date: 25/05/2020
description: |
  This is my quick guide to lining a pastry case and blind baking it. If it is used in a recipe then the timings for baking the case might change but the method will remain the same.
tags:
  - pastry
images:
  - /recipes/blind_baking/Blind_Baking.jpg
ingredients:
  - 1 quantity of sweet pastry
method:
  - Get your pastry out of the fridge, if it is too hard to work with give it a small knead until it becomes pliable. Lightly flour your surface and roll the pastry into a round big enough to cover your tart case. Gently lower it into the sides by picking the pastry up near the edges and letting it fall into the bottom of the case, finally pressing it down into the bottom of the case.
  - Roll over the top of the case, removing the excess. If you have a fluted tin, use your forefinger to push the pastry into the dips, resting your thumb just above the case as you do so. This will created a fluted edge. Cover and place in the fridge for at least 20 minutes.
  - Whilst your pastry case is cooling, preheat the oven to 180°C. Cut a piece of greaseproof paper slightly larger than your tart case. You want to scrunch the piece of paper a few times, without tearing it, so it falls into the case more easily. Place the greaseproof in your cooled pastry case and fill it with baking beans. You could use rice, or dried chickpeas/lentils instead, as long as they are not too large. Cook for 10 mins.
  - Remove the case from the oven and take the baking beans and greaseproof out of the case. Prick the bottom of the pastry case with a fork all over and place back in the oven for another 10 minutes (or longer if you are cooking the pastry completely, see recipes). You want to keep an eye out for any bubbles that rise from the bottom of the case, if this happens simply prick them with a fork.
  - Once the pastry is dry on the bottom, and starting to go golden on the edges, remove from the oven and leave to cool.
