template: recipe
directory: recipe
title: Chocolate Tiffin
card_photo: /recipes/tiffin/Chocolate_Tiffin_Square.jpg
instagram: https://www.instagram.com/p/BtJikIWhz7_/?utm_source=ig_web_copy_link
featured: true
description: |
  This recipe was given to me by my boyfriend's family, and I love it.
  It's really quick to make and requires no baking in the oven - plus it's heavenly to eat.
tags:
  - Chocolate
  - Yummy
images:
  - /recipes/tiffin/Chocolate_Tiffin_Square.jpg
ingredients:
  - 120g butter
  - 2 tbsp cocoa powder
  - 1 tbsp caster sugar
  - 1 tbsp golden syrup
  - 230g digestives, crushed
  - 200g dark chocolate (or depending on the size of your tin)
  - Optional, 60g dried fruit
method:
  - Crush the digestives with the end of a rolling pin, or in a food processor.
  - On a medium heat, melt the butter with the sugar, golden syrup and cocoa powder. Stir in the biscuits and mix until everything is combined.
    It might take a while for everything to bind.
  - Line an 8 by 8 inch cake tin, and then press the mix into the tin until completely compacted. Leave in the fridge for 20 minutes to set.
  - Melt the chocolate, either in the microwave or over a bain marie. Spread over the top of the tiffin and leave to cool in the fridge until hard. When set, cut into 16 squares and enjoy.
  - How to adapt. If you want to, add some dried fruit, or a favourite of mine is to add some orange zest to the mix.
